-- Drop bảng KQHOCKYTONGHOP
DROP TABLE KQHOCKYTONGHOP;

-- Drop bảng KQHOCKYMONHOC
DROP TABLE KQHOCKYMONHOC;

-- Drop bảng KQNAMHOC
DROP TABLE KQNAMHOC;

-- Drop bảng PHANCONGGIANGDAY
DROP TABLE PHANCONGGIANGDAY;

-- Drop bảng KHANANGGIANGDAY
DROP TABLE KHANANGGIANGDAY;

-- Drop bảng KETQUA
DROP TABLE KETQUA;

-- Drop bảng HANHKIEM
DROP TABLE HANHKIEM;

-- Drop bảng HOCLUC
DROP TABLE HOCLUC;

-- Drop bảng DIEMMONHOC
DROP TABLE DIEMMONHOC;

-- Drop bảng LOAIKIEMTRA
DROP TABLE LOAIKIEMTRA;

-- Drop bảng LOPHOCTHUCTE_HOCSINH
DROP TABLE LOPHOCTHUCTE_HOCSINH;

-- Drop bảng LOPHOCTHUCTE
DROP TABLE LOPHOCTHUCTE;

-- Drop bảng LOP
DROP TABLE LOP;

-- Drop bảng MONHOC
DROP TABLE MONHOC;

-- Drop bảng PHHS
DROP TABLE PHHS;

-- Drop bảng HOCSINH
DROP TABLE HOCSINH;

-- Drop bảng NHANVIENPHONGDAOTAO
DROP TABLE NHANVIENPHONGDAOTAO;

-- Drop bảng GIAOVIEN
DROP TABLE GIAOVIEN;

-- Drop bảng TAIKHOAN
DROP TABLE TAIKHOAN;

-- Drop bảng HOCKY
DROP TABLE HOCKY;

-- Drop bảng NAMHOC
DROP TABLE NAMHOC;

-- Drop bảng THAMSO
DROP TABLE THAMSO;
